INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$1', 'good move (traditional \"!\") see also Nunn Convention for alternate meanings', '!', 'U+0021', '&excl;', 'single exclamation mark');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$2','poor move or mistake (traditional "?") (and Nunn Convention)','?','U+003F','&quest;','single question mark');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$3','very good or brilliant move (traditional "!!") (and Nunn Convention)','‼','U+203C','&#x203C;','double exclamation mark');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$4','very poor move or blunder (traditional "??") (and Nunn Convention)','⁇','U+2047','&#x2047;','double question mark');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$5','speculative or interesting move (traditional "!?") (and Nunn Convention)','⁉','U+2049','&#x2049;','exclamation question mark');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$6','questionable or dubious move (traditional "?!") (and Nunn Convention)','⁈','U+2048','&#x20498','question mark and exclamation mark');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$7','forced move (all others lose quickly) or only move','□','U+25A1','&square;','white square');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$8','singular move (no reasonable alternatives)');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$9','worst move');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$10','drawish position or even','=','U+003D','&equals;','equal sign');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$11','equal chances, quiet position');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$12','equal chances, active position');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$13','unclear position','∞','U+221E','&infin;','infinity');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$14','White has a slight advantage','⩲','U+2A72','&pluse;','plus sign above equals sign');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$15','Black has a slight advantage','⩱','U+2A71','&eplus;','equals sign above plus sign');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$16','White has a moderate advantage','±','U+00B1','&plusmn;','plus-minus sign');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$17','Black has a moderate advantage','∓','U+2213','&mnplus;','minus-or-plus sign');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$18','White has a decisive advantage','+ −','U+002B U+002D','&plus; &#45;','plus sign, hyphen-minus sign');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$19','Black has a decisive advantage','− +','U+002D U+002B','&#45; &plus;','hyphen-minus sign, plus sign');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$20','White has a crushing advantage (Black should resign)');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$21','Black has a crushing advantage (White should resign)');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$22','White is in zugzwang','⨀','U+2A00','&xodot;','N-ary circled dot operator');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$23','Black is in zugzwang','⨀','U+2A00','&xodot;','N-ary circled dot operator');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$24','White has a slight space advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$25','Black has a slight space advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$26','White has a moderate space advantage','○','U+25CB','&#x25cb;','White circle');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$27','Black has a moderate space advantage','○','U+25CB','&#x25cb;','White circle');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$28','White has a decisive space advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$29','Black has a decisive space advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$30','White has a slight time (development) advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$31','Black has a slight time (development) advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$32','White has a moderate time (development) advantage','⟳','U+27F3','&#x27F3;','clockwise gapped circle arrow');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$33','Black has a moderate time (development) advantage','⟳','U+27F3','&#x27F3;','clockwise gapped circle arrow');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$34','White has a decisive time (development) advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$35','Black has a decisive time (development) advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$36','White has the initiative','↑','U+2191','&uarr;','upwards arrow');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$37','Black has the initiative','↑','U+2191','&uarr;','upwards arrow');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$38','White has a lasting initiative');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$39','Black has a lasting initiative');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$40','White has the attack','→','U+2192','&rarr;','rightwards arrow');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$41','Black has the attack','→','U+2192','&rarr;','rightwards arrow');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$42','White has insufficient compensation for material deficit');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$43','Black has insufficient compensation for material deficit');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$44','White has sufficient compensation for material deficit','⯹','U+2BF9','&#x2bf9;','equals sign with infinity below');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$45','Black has sufficient compensation for material deficit','⯹','U+2BF9','&#x2bf9;','equals sign with infinity below');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$46','White has more than adequate compensation for material deficit');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$47','Black has more than adequate compensation for material deficit');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$48','White has a slight center control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$49','Black has a slight center control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$50','White has a moderate center control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$51','Black has a moderate center control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$52','White has a decisive center control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$53','Black has a decisive center control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$54','White has a slight kingside control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$55','Black has a slight kingside control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$56','White has a moderate kingside control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$57','Black has a moderate kingside control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$58','White has a decisive kingside control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$59','Black has a decisive kingside control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$60','White has a slight queenside control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$61','Black has a slight queenside control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$62','White has a moderate queenside control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$63','Black has a moderate queenside control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$64','White has a decisive queenside control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$65','Black has a decisive queenside control advantage');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$66','White has a vulnerable first rank');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$67','Black has a vulnerable first rank');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$68','White has a well protected first rank');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$69','Black has a well protected first rank');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$70','White has a poorly protected king');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$71','Black has a poorly protected king');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$72','White has a well protected king');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$73','Black has a well protected king');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$74','White has a poorly placed king');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$75','Black has a poorly placed king');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$76','White has a well placed king');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$77','Black has a well placed king');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$78','White has a very weak pawn structure');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$79','Black has a very weak pawn structure');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$80','White has a moderately weak pawn structure');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$81','Black has a moderately weak pawn structure');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$82','White has a moderately strong pawn structure');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$83','Black has a moderately strong pawn structure');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$84','White has a very strong pawn structure');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$85','Black has a very strong pawn structure');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$86','White has poor knight placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$87','Black has poor knight placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$88','White has good knight placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$89','Black has good knight placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$90','White has poor bishop placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$91','Black has poor bishop placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$92','White has good bishop placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$93','Black has good bishop placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$94','White has poor rook placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$95','Black has poor rook placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$96','White has good rook placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$97','Black has good rook placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$98','White has poor queen placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$99','Black has poor queen placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$100','White has good queen placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$101','Black has good queen placement');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$102','White has poor piece coordination');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$103','Black has poor piece coordination');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$104','White has good piece coordination');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$105','Black has good piece coordination');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$106','White has played the opening very poorly');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$107','Black has played the opening very poorly');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$108','White has played the opening poorly');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$109','Black has played the opening poorly');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$110','White has played the opening well');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$111','Black has played the opening well');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$112','White has played the opening very well');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$113','Black has played the opening very well');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$114','White has played the middlegame very poorly');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$115','Black has played the middlegame very poorly');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$116','White has played the middlegame poorly');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$117','Black has played the middlegame poorly');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$118','White has played the middlegame well');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$119','Black has played the middlegame well');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$120','White has played the middlegame very well');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$121','Black has played the middlegame very well');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$122','White has played the ending very poorly');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$123','Black has played the ending very poorly');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$124','White has played the ending poorly');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$125','Black has played the ending poorly');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$126','White has played the ending well');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$127','Black has played the ending well');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$128','White has played the ending very well');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$129','Black has played the ending very well');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$130','White has slight counterplay');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$131','Black has slight counterplay');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$132','White has moderate counterplay','⇆','U+21C6','&lrarr;','leftwards arrow over rightwards arrow');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$133','Black has moderate counterplay','⇆','U+21C6','&lrarr;','leftwards arrow over rightwards arrow');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$134','White has decisive counterplay');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$135','Black has decisive counterplay');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$136','White has moderate time control pressure');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`) VALUES(0, '$137','Black has moderate time control pressure');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$138','White has severe time control pressure / zeitnot','⨁','U+2A01','&xoplus;','n-ary circle plus operator');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$139','Black has severe time control pressure / zeitnot','⨁','U+2A01','&xoplus;','n-ary circle plus operator');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$140','With the idea...','∆','U+2206','&#x2206;','increment');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$141','Aimed against...','∇','U+2207','&#x2207;','nabla');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$142','Better is...','⌓','U+2313','&profsurf;','segment');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$143','Worse is...','<=','U+003C U+003D','&lt;&equals;','less than, equal to');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$144','Equivalent is...','==','U+003D U+003D','&equals;&equals;','equal to, equal to');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$145','Editorial comment','RR','U+0052 U+0052','RR','capital R, capital R');
INSERT INTO `T_NAG` (`Id`, `DollarIndex`, `Bedeutung`, `Symbolzeichen`, `Unicode`, `html`, `Symbolname`) VALUES(0, '$146','Novelty','N','U+004E','N','capital N');
